# -*- coding: utf-8 -*-
##############################################################################
# Copyright (c) 2015-Present Webkul Software Pvt. Ltd. (<https://webkul.com/>)
# See LICENSE file for full copyright and licensing details.
# License URL : <https://store.webkul.com/license.html/>
##############################################################################

GSTTYPECOLUMN = {
    "b2b_gstr1": [
        "GSTIN/UIN of Recipient",
        "Receiver Name",
        "Invoice Number",
        "Invoice date",
        "Invoice Value",
        "Place Of Supply",
        "Reverse Charge",
        "Applicable % of Tax Rate",
        "Invoice Type",
        "E-Commerce GSTIN",
        "Rate",
        "Taxable Value",
        "Cess Amount",
    ],
    "b2b_gstr2": [
        "GSTIN of Supplier",
        "Invoice Number",
        "Invoice date",
        "Invoice Value",
        "Place Of Supply",
        "Reverse Charge",
        "Invoice Type",
        "Rate",
        "Taxable Value",
        "Integrated Tax Paid",
        "Central Tax Paid",
        "State/UT Tax Paid",
        "Cess Amount",
        "Eligibility For ITC",
        "Availed ITC Integrated Tax",
        "Availed ITC Central Tax",
        "Availed ITC State/UT Tax",
        "Availed ITC Cess",
    ],
    "b2bur": [
        "Supplier Name",
        "Invoice Number",
        "Invoice date",
        "Invoice Value",
        "Place Of Supply",
        "Supply Type",
        "Rate",
        "Taxable Value",
        "Integrated Tax Paid",
        "Central Tax Paid",
        "State/UT Tax Paid",
        "Cess Amount",
        "Eligibility For ITC",
        "Availed ITC Integrated Tax",
        "Availed ITC Central Tax",
        "Availed ITC State/UT Tax",
        "Availed ITC Cess",
    ],
    "b2cs": [
        "Type",
        "Place Of Supply",
        "Applicable % of Tax Rate",
        "Rate",
        "Taxable Value",
        "Cess Amount",
        "E-Commerce GSTIN",
    ],
    "b2cl": [
        "Invoice Number",
        "Invoice date",
        "Invoice Value",
        "Place Of Supply",
        "Applicable % of Tax Rate",
        "Rate",
        "Taxable Value",
        "Cess Amount",
        "E-Commerce GSTIN",
    ],
    "export": [
        "Export Type",
        "Invoice Number",
        "Invoice date",
        "Invoice Value",
        "Port Code",
        "Shipping Bill Number",
        "Shipping Bill Date",
        "Applicable % of Tax Rate",
        "Rate",
        "Taxable Value",
    ],
    "cdnr_gstr1": [
        "GSTIN/UIN of Recipient",
        "Receiver Name",
        "Note Number",
        "Note Date",
        "Note Type",
        "Place Of Supply",
        "Reverse Charge",
        "Note Supply Type",
        "Note Value",
        "Applicable % of Tax Rate",
        "Rate",
        "Taxable Value",
        "Cess Amount",
    ],
    "cdnr_gstr2": [
        "GSTIN of Supplier",
        "Note/Refund Voucher Number",
        "Note/Refund Voucher date",
        "Invoice/Advance Payment Voucher Number",
        "Invoice/Advance Payment Voucher date",
        "Reverse Charge",
        "Document Type",
        "Reason For Issuing document",
        "Supply Type",
        "Note/Refund Voucher Value",
        "Rate",
        "Taxable Value",
        "Integrated Tax Paid",
        "Central Tax Paid",
        "State/UT Tax Paid",
        "Cess Paid",
        "Eligibility For ITC",
        "Availed ITC Integrated Tax",
        "Availed ITC Central Tax",
        "Availed ITC State/UT Tax",
        "Availed ITC Cess",
    ],
    "cdnur_gstr1": [
        "UR Type",
        "Note Number",
        "Note Date",
        "Note Type",
        "Place Of Supply",
        "Note Value",
        "Applicable % of Tax Rate",
        "Rate",
        "Taxable Value",
        "Cess Amount",
    ],
    "imps": [
        "Invoice Number of Reg Recipient",
        "Invoice Date",
        "Invoice Value",
        "Place Of Supply",
        "Rate",
        "Taxable Value",
        "Integrated Tax Paid",
        "Cess Amount",
        "Eligibility For ITC",
        "Availed ITC Integrated Tax",
        "Availed ITC Cess",
    ],
    "impg": [
        "Port Code",
        "Bill Of Entry Number",
        "Bill Of Entry Date",
        "Bill Of Entry Value",
        "Document type",
        "GSTIN Of SEZ Supplier",
        "Rate",
        "Taxable Value",
        "Integrated Tax Paid",
        "Cess Amount",
        "Eligibility For ITC",
        "Availed ITC Integrated Tax",
        "Availed ITC Cess",
    ],
    "hsn": [
        "HSN",
        "Description",
        "UQC",
        "Total Quantity",
        "Total Value",
        "Rate",
        "Taxable Value",
        "Integrated Tax Amount",
        "Central Tax Amount",
        "State/UT Tax Amount",
        "Cess Amount",
    ],
}
